# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FXBusinessEngineKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FXBusinessEngineKit
 pod 'SDWebImage'
 pod 'Alamofire'
 pod 'LookinServer'
 pod 'SnapKit'
 pod 'Toast-Swift'
 pod 'KeychainAccess'
 pod 'CocoaLumberjack/Swift'

 post_install do |installer|
   installer.pods_project.targets.each do |target|
       target.build_configurations.each do |config|
           config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
           config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
       end
   end
   end
 
end
